name: Concurrency 2
on:
    workflow_dispatch:
        inputs:
            environment:
                required: true

jobs:
    sleep:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 30 