name: Concurrency 1
on:
    workflow_dispatch:
        inputs:
            environment:
                required: true

concurrency: concurrency-1
jobs:
    sleep:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 30 