name: My-Workflow
on: 
    workflow_dispatch

jobs:
    deploy-docker-containers:
        runs-on: ubuntu-latest
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        steps:
        - name: Login to DockerHub Registry
          run: echo ${{ env.DOCKER_PASSWORD }} | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin
        - name: Container in a Step Alpine
          uses: docker://alpine
        - name: Container in a Step Ubuntu
          uses: docker://ubuntu
        - name: Container in a Step Mint
          uses: docker://linuxmint/mint19.3-amd64
        - name: Container in a Step Debian
          uses: docker://debian

        - name: Retrieve the running docker containers from the host
          run: |
            docker ps -a > running_containers.txt
            cat running_containers.txt



        

    # connect-to-the-containers:
    #     needs: deploy-docker-containers
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Connect to the container
    #       run: |
            
         