name: Simple Action
on: [push]
jobs:
    simple-action:
        runs-on: ubuntu-latest
        steps:
            - name: Simple Docker Action
              id: greet
              uses: ./.github/actions/hello-docker
              with: 
                who-to-greet: Costin
            - name: Log Greeting Time
              run: echo "${{ steps.greet.outputs.time }}"
            - name: Log ENV Var
              run: echo $HELLO_TIME