name: Calling Reusable Workflows
on:
    workflow_dispatch:
        inputs:
            name:
              description: 'Input description'
              type: string
              default: 'Costin'
              required: false
jobs:
    calling-a-reusable-wf:
        uses: github-actions-course2/workflows/.github/workflows/reusable.yaml@main
        with:
            name: ${{ inputs.name }}
        secrets:
            access-token: ${{ secrets.ACCESS_TOKEN }}